__author__ = 'Administrator'
from selenium import webdriver
from time import sleep
browser = webdriver.Firefox()
sleep(2)
browser.get("http://127.0.0.1:8080/oa")
sleep(2)
browser.find_element_by_css_selector('.loginInput').clear()
sleep(2)
browser.find_element_by_css_selector('[name="loginId"]').send_keys('sup')
sleep(2)
browser.find_element_by_css_selector('[type="text"]').clear()
sleep(2)
browser.find_element_by_css_selector('[tabindex="1"]').send_keys('sup')
sleep(2)
browser.find_element_by_css_selector('[tabindex="1"]').clear()
sleep(2)
browser.find_element_by_css_selector('.loginInput[name="loginId"][type="text"][tabindex="1"]').send_keys('sup')
sleep(2)
browser.find_element_by_css_selector('.loginInput[name="password"][type="password"][tabindex="2"]').send_keys('s1234567')
sleep(2)
browser.find_element_by_css_selector("#button_submit").click()